import type { Metadata } from "next";
import Link from "next/link";
import { LEGAL_CONFIG } from "@/lib/legal-config";

// Title kept as just the label ("Privacy Policy"), not the old hand-appended
// "Privacy Policy | ATBP": the root layout's title template now appends
// " | ATBP" itself, so a literal "| ATBP" baked in here would double up.
const PRIVACY_TITLE = "Privacy Policy";
const PRIVACY_DESCRIPTION =
  "Read the ATBP Privacy Policy: what personal data we collect, how it's used and shared, your rights under the Data Privacy Act, and how to contact us.";

export const metadata: Metadata = {
  title: PRIVACY_TITLE,
  description: PRIVACY_DESCRIPTION,
  openGraph: { title: PRIVACY_TITLE, description: PRIVACY_DESCRIPTION, images: ["/opengraph-image"], type: "website" },
  twitter: { card: "summary_large_image", title: PRIVACY_TITLE, description: PRIVACY_DESCRIPTION },
};

const LAST_UPDATED = "September 19, 2026";

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 pb-16 pt-8 md:px-6">
      <h1 className="font-display text-3xl font-semibold text-ink-900">Privacy Policy</h1>
      <p className="mt-3 text-sm text-ink-500">Last Updated: {LAST_UPDATED}</p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-ink-700">
        <p>
          This Privacy Policy explains how <Placeholder>{LEGAL_CONFIG.entityName}</Placeholder>, operating ATBP at{" "}
          <Placeholder>{LEGAL_CONFIG.entityAddress}</Placeholder> (&quot;ATBP,&quot; &quot;we,&quot; &quot;us&quot;), collects, uses,
          discloses, and protects personal data in connection with the ATBP Platform, as the Personal Information
          Controller for that data, in accordance with the Data Privacy Act of 2012 (Republic Act No. 10173) and its
          Implementing Rules and Regulations.
        </p>

        <Section title="1. Privacy Contact">
          <p>
            For any question, request, or complaint about this Policy or your personal data, contact ATBP at{" "}
            <a href={`mailto:${LEGAL_CONFIG.privacyContactEmail}`} className="font-semibold text-brand-600 hover:underline">{LEGAL_CONFIG.privacyContactEmail}</a>.
            Designated privacy contact / Data Protection Officer: <Placeholder>{LEGAL_CONFIG.dpoNameOrContact}</Placeholder>.
          </p>
        </Section>

        <Section title="2. Information We Collect">
          <ul className="list-disc space-y-1.5 pl-5">
            <li><strong className="text-ink-900">Account information</strong>, which you provide directly: name, email address, phone number, username, password (stored hashed, never in plain text), and profile details you choose to add.</li>
            <li><strong className="text-ink-900">Seller verification information</strong>, which you provide directly during Seller onboarding: a government-issued ID, and, for a Seller applying as a registered business, a BIR Certificate of Registration and business registration number. These documents are reviewed by ATBP staff for verification only and are never published on a Seller&apos;s public shop page.</li>
            <li><strong className="text-ink-900">Transaction information</strong>, generated by using the Platform: order history, items purchased or sold, delivery/pickup addresses, and payment status. ATBP does not directly collect or store complete payment card numbers; those are handled by the payment method integration used at checkout.</li>
            <li><strong className="text-ink-900">Location information</strong>, which you provide directly: the city/province you select for browse-by-city discovery, local pickup, and delivery matching.</li>
            <li><strong className="text-ink-900">Content you provide</strong>: listing photos and descriptions, messages between Users, reviews, and support requests.</li>
            <li><strong className="text-ink-900">Technical information</strong>, collected automatically: IP address, device and browser type, and pages visited, collected through the essential and analytics technologies described in Section 9 (Cookies).</li>
          </ul>
        </Section>

        <Section title="3. Sources of Information">
          <p>
            Most personal data comes directly from you, when you create an account, complete your profile, apply as
            a Seller, place or fulfil an order, or message another User. Some information (device/browser data, page
            activity) is collected automatically as you use the Platform. Where you sign in using Google or Facebook,
            we receive the name, email address, and profile photo that provider shares with us under your permission
            to that provider, not anything beyond what you&apos;ve authorized there.
          </p>
        </Section>

        <Section title="4. How We Use Personal Data">
          <p>
            We use personal data to: operate and maintain the Platform and User accounts; process orders and, where
            a Seller is owed proceeds, calculate and record payouts; verify Seller identity and business
            registration; facilitate local pickup and delivery matching; enable messaging and reviews between Users;
            provide customer support and handle complaints under our redress mechanism; send transactional messages
            (order updates, account notices) and, where you&apos;ve consented, marketing communications; detect and
            prevent fraud, abuse, and violations of our Terms of Service; and comply with legal and regulatory
            obligations, including those under the Internet Transactions Act (RA 11967).
          </p>
        </Section>

        <Section title="5. Legal Basis and Consent">
          <p>
            We process personal data on the basis of your consent (given when you create an account and agree to
            this Policy), the necessity of processing to perform our contract with you (fulfilling orders, providing
            the marketplace service), and compliance with our legal obligations. You may withdraw consent for
            non-essential processing (such as marketing communications) at any time through your account settings or
            by contacting us.
          </p>
        </Section>

        <Section title="6. Sharing With Sellers (Buyer-to-Seller Data)">
          <div className="space-y-3">
            <p>
              When you buy something on ATBP, ATBP shares the information the Seller needs to fulfil that specific
              order with the Seller: your name, delivery address (or pickup arrangement details), phone number, and
              the order/product details. For a message you send a Seller, that Seller sees what you send them. ATBP
              does not give a Seller access to your payment card or wallet details, your full order history with
              other Sellers, or any personal data beyond what that particular order or conversation requires.
            </p>
            <p>
              <strong className="text-ink-900">Sellers must only use a Buyer&apos;s information for the transaction it
              was shared for, and for a Seller&apos;s own applicable legal obligations (such as tax or shipping
              records).</strong> A Seller must not: sell or rent Buyer information to anyone; share it with an
              unrelated third party; use it for marketing unrelated to that order; add a Buyer to the Seller&apos;s own
              marketing list without the Buyer&apos;s separate, appropriate consent; or use it for any purpose unrelated
              to fulfilling that transaction. A Seller who misuses Buyer information this way is in breach of the{" "}
              <Link href="/terms" className="font-semibold text-brand-600 hover:underline">Terms of Service</Link>{" "}
              and may have their account suspended or terminated.
            </p>
          </div>
        </Section>

        <Section title="7. Other Sharing and Disclosure">
          <p>
            Beyond the Buyer-to-Seller sharing above, we share personal data only as necessary with: the third-party
            service providers listed in Section 8, to the extent each one needs to do its job; and government
            agencies or regulators where required by law, such as in response to a valid legal order or under the
            Internet Transactions Act. We do not sell personal data to third parties.
          </p>
        </Section>

        <Section title="8. Third-Party Service Providers">
          <p className="mb-2">ATBP currently uses the following categories of third-party service provider. This list reflects what the Platform actually uses today, and will be updated if that changes:</p>
          <ul className="list-disc space-y-1.5 pl-5">
            <li><strong className="text-ink-900">Hosting, infrastructure, and file storage</strong> (Vercel): runs the Platform and stores uploaded images, videos, and files.</li>
            <li><strong className="text-ink-900">Database hosting</strong> (Neon, a managed PostgreSQL provider): stores account, listing, and order records.</li>
            <li><strong className="text-ink-900">Sign-in</strong>: ATBP&apos;s own authentication system, plus optional &quot;Sign in with Google&quot; and &quot;Sign in with Facebook,&quot; which share the name, email, and profile photo you&apos;ve authorized with those providers.</li>
            <li><strong className="text-ink-900">Transactional email</strong> (ZeptoMail, a Zoho product): delivers account, order, and password-reset emails.</li>
            <li><strong className="text-ink-900">Site and product analytics</strong> (Vercel Analytics and PostHog): count page views and how people move through the Platform (for example, whether a sign-up or checkout is completed) without using tracking cookies, storing anything in your browser, or building an advertising profile. Staff pages are never included, and we do not send your name, email, address, or messages to these tools.</li>
            <li><strong className="text-ink-900">Error monitoring</strong> (Sentry): receives technical error reports (e.g., a crashed page) to help us fix bugs; this can incidentally include the URL and account ID involved in an error, not your message or listing content.</li>
          </ul>
          <p className="mt-3 text-ink-600">
            ATBP does not currently use a third-party payment processor, payout processor, SMS provider, or courier
            API to move real transactions, payouts, text messages, or shipments; checkout, payouts, and shipping on
            the Platform run through ATBP&apos;s own systems today. If ATBP connects a real payment processor, payout
            provider, SMS provider, or shipping courier&apos;s API in the future, this Policy will be updated to name
            that provider and explain what it processes before that change takes effect.
          </p>
        </Section>

        <Section title="9. Cookies and Tracking">
          <p>
            The Platform currently uses only cookies that are strictly necessary for it to function: a session cookie
            that keeps you logged in, and a cookie that remembers the city/area you&apos;ve selected for local
            discovery. Neither is used for advertising, and neither is shared with an ad network. Site analytics
            (Section 8) is cookieless. Because the Platform does not currently set any non-essential or advertising
            cookie, it does not currently show a cookie-consent banner; if that changes, this Policy and the
            Platform will be updated together, with a consent mechanism added before any non-essential cookie is set.
            You can still block or delete cookies through your browser&apos;s own settings at any time, though doing so
            may sign you out or reset your saved area.
          </p>
        </Section>

        <Section title="10. International Data Transfers">
          <p>
            Some of our service providers (see Section 8) may process or store personal data on servers located
            outside the Philippines as part of their own global infrastructure. Where this occurs, we choose
            providers that maintain a comparable standard of data protection, consistent with the Data Privacy Act&apos;s
            requirements for cross-border data transfers.
          </p>
        </Section>

        <Section title="11. Data Retention">
          <p className="mb-2">
            We keep personal data only as long as needed for the purpose it was collected for, or as long as
            applicable law requires. Where an exact period depends on a legal requirement (tax, corporate
            recordkeeping, or a payment provider&apos;s own rules) rather than ATBP&apos;s own choice, that&apos;s noted below
            instead of a specific number of days, since it isn&apos;t ATBP&apos;s to set unilaterally.
          </p>
          <div className="overflow-x-auto rounded-2xl border border-ink-100">
            <table className="w-full text-left text-xs">
              <thead className="bg-ink-50 text-ink-500">
                <tr>
                  <th className="p-3 font-semibold">Category</th>
                  <th className="p-3 font-semibold">Retention</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-ink-100">
                <tr>
                  <td className="p-3 font-semibold text-ink-800">Account information</td>
                  <td className="p-3 text-ink-600">While your account is active, plus a limited period after closure to handle any follow-up dispute or legal obligation.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-ink-800">Order and transaction records</td>
                  <td className="p-3 text-ink-600">As required for Philippine tax and business recordkeeping obligations, which ATBP has not independently shortened.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-ink-800">Seller verification documents (ID, BIR registration)</td>
                  <td className="p-3 text-ink-600">For as long as needed to keep the Seller account verified, and thereafter as required by applicable business/legal recordkeeping requirements.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-ink-800">Payment-related records</td>
                  <td className="p-3 text-ink-600">As required by applicable tax, accounting, and (once a real payment provider is connected) that provider&apos;s own recordkeeping requirements.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-ink-800">Customer support and dispute records</td>
                  <td className="p-3 text-ink-600">Long enough to handle a follow-up complaint, appeal, or legal claim related to that case.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-ink-800">Marketing preferences</td>
                  <td className="p-3 text-ink-600">Until you withdraw consent, plus a short record that you did so.</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold text-ink-800">Fraud/security records</td>
                  <td className="p-3 text-ink-600">Long enough to investigate and to prevent repeat abuse, consistent with applicable law.</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="mt-2 text-xs text-ink-500">
            When data is no longer needed for any of these purposes, we securely delete or anonymize it.
          </p>
        </Section>

        <Section title="12. Your Rights Under the Data Privacy Act">
          <p>Subject to applicable law, you have the right to:</p>
          <ul className="mt-2 list-disc space-y-1.5 pl-5">
            <li>be informed that your personal data will be, is being, or was processed;</li>
            <li>access your personal data;</li>
            <li>request correction of inaccurate or outdated data;</li>
            <li>request erasure or blocking of data that is no longer necessary, unlawfully obtained, or used for unauthorized purposes;</li>
            <li>object to processing, including for direct marketing;</li>
            <li>data portability, where technically feasible; and</li>
            <li>lodge a complaint with the National Privacy Commission (NPC).</li>
          </ul>
          <p className="mt-2">
            You can delete your account yourself from Settings (&quot;Delete account&quot;). To exercise your other rights, or
            if you can&apos;t sign in, contact us at{" "}
            <a href={`mailto:${LEGAL_CONFIG.privacyContactEmail}`} className="font-semibold text-brand-600 hover:underline">{LEGAL_CONFIG.privacyContactEmail}</a>{" "}
            or through the{" "}
            <Link href="/help/contact" className="font-semibold text-brand-600 hover:underline">contact form</Link>.
            Deleting your account removes your name, email, phone number, addresses, and any ID files, and it cannot be
            undone. It does not erase records ATBP is legally required to keep (for example, completed order and tax
            records), which are kept without your name attached to your profile.
          </p>
        </Section>

        <Section title="13. Marketing Communications">
          <p>
            We only send marketing communications (as opposed to transactional messages about your own orders or
            account) if you&apos;ve opted in, and every marketing message includes a way to opt out. Opting out of
            marketing does not stop transactional messages needed to service your account or orders.
          </p>
        </Section>

        <Section title="14. Security Measures">
          <p>
            We apply reasonable technical and organizational safeguards to protect personal data, including
            encrypted connections (HTTPS/TLS) between your device and the Platform, encryption of stored data at
            rest through our infrastructure providers, hashed (not plain-text) passwords, rate limiting against
            automated abuse, role-based access controls for ATBP staff, and audit logging of administrative actions.
            No system is completely secure, and we cannot guarantee absolute security; we work to reduce risk and to
            respond quickly if something goes wrong, as described in the next section.
          </p>
        </Section>

        <Section title="15. Data Breach Notification">
          <p>
            If a personal data breach occurs that is likely to give rise to a real risk of serious harm to affected
            Users, ATBP will notify the National Privacy Commission and affected Users within the timeframe required
            by NPC regulations, and will take reasonable steps to contain and address the breach.
          </p>
        </Section>

        <Section title="16. Children&apos;s Privacy">
          <p>
            The Platform is not directed to, and Users must be at least 18 years old or the age of majority in their
            jurisdiction. We do not knowingly collect personal data from minors.
          </p>
        </Section>

        <Section title="17. Changes to This Policy">
          <p>
            We may update this Privacy Policy from time to time. Material changes will be notified to Users through
            the Platform or by email before taking effect.
          </p>
        </Section>

        <Section title="18. Contact Us">
          <p>
            For questions, requests, or complaints regarding this Policy or your personal data, contact:{" "}
            <a href={`mailto:${LEGAL_CONFIG.privacyContactEmail}`} className="font-semibold text-brand-600 hover:underline">{LEGAL_CONFIG.privacyContactEmail}</a>.
          </p>
        </Section>

        <p className="text-xs text-ink-400">
          See also our <Link href="/terms" className="font-semibold text-brand-600 hover:underline">Terms of Service</Link>, which this Policy forms part of.
        </p>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-display mb-2 text-lg font-semibold text-ink-900">{title}</h2>
      {children}
    </section>
  );
}

/** Marks a value that must be filled in before launch — deliberately left as
 * visible placeholder text rather than an invented value. Sourced from
 * LEGAL_CONFIG so there's exactly one place to update once confirmed. */
function Placeholder({ children }: { children: React.ReactNode }) {
  return <span className="rounded bg-gold-100 px-1.5 py-0.5 font-mono text-[13px] font-semibold text-gold-700">{children}</span>;
}
